DEFINE
    MEASURE PBIpull[calrefor] =
        CALCULATE ( SUM ( 'PBIpull'[Count] ), 'PBIpull'[Type] = "08&04 Reforecast" )
    -- 22494
    MEASURE PBIpull[rfmix] =
        MAX ( 'PBIpull'[Type] ) = "08&04 Reforecast"
            && MIN ( 'PBIpull'[Year Month Code] ) <= 202206
    MEASURE PBIpull[calreless] =
        CALCULATE ( SUM ( 'PBIpull'[Count] ), 'PBIpull'[Type] = "Actuals" )
    MEASURE PBIpull[sumresult] =
        SUM ( 'PBIpull'[Count] )
    MEASURE PBIpull[Original] =
        SWITCH (
            TRUE (),
            MAX ( 'PBIpull'[Type] ) = "08&04 Reforecast"
                && MIN ( 'PBIpull'[Year Month Code] ) <= 202206, CALCULATE ( SUM ( 'PBIpull'[Count] ), 'PBIpull'[Type] = "Actuals" ),
            CALCULATE ( SUM ( 'PBIpull'[Count] ) )
        )
    MEASURE PBIpull[MeasureX] =
        SWITCH (
            TRUE (),
            MAX ( 'PBIpull'[Type] ) = "08&04 Reforecast"
                && MIN ( 'PBIpull'[Year Month Code] ) >= 202207, CALCULATE ( SUM ( 'PBIpull'[Count] ), 'PBIpull'[Type] = "08&04 Reforecast" ),
            MAX ( 'PBIpull'[Type] ) = "08&04 Reforecast"
                && MIN ( 'PBIpull'[Year Month Code] ) <= 202206, CALCULATE ( SUM ( 'PBIpull'[Count] ), 'PBIpull'[Type] = "Actuals" ),
            CALCULATE ( SUM ( 'PBIpull'[Count] ) )
        )
    -- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::    
    -- CORRECT 
MEASURE PBIpull[Correct] =
        SWITCH (
            TRUE (),
            MAX ( 'PBIpull'[Type] ) = "08&04 Reforecast"
                && MIN MAX ( 'PBIpull'[Type] ) = "08&04 Reforecast"
                && MIN ( 'PBIpull'[Year Month Code] ) >= 202207,( 'PBIpull'[Year Month Code] ) >= 202207, CALCULATE ( SUM ( 'PBIpull'[Count] ), 'PBIpull'[Type] = "08&04 Reforecast" ),
            MAX ( 'PBIpull'[Type] ) = "Actuals"
                && MIN ( 'PBIpull'[Year Month Code] ) <= 202206, CALCULATE ( SUM ( 'PBIpull'[Count] ), 'PBIpull'[Type] = "Actuals" ),
            CALCULATE ( SUM ( 'PBIpull'[Count] ) )
        )
    -- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    MEASURE PBIpull[rfmax] =
        MAX ( 'PBIpull'[Type] ) = "08&04 Reforecast"
            && MIN ( 'PBIpull'[Year Month Code] ) >= 202207
    -- FALSE        
    MEASURE PBIpull[maxVal] =
        CALCULATE ( MAX ( 'PBIpull'[Type] ) )
    MEASURE PBIpull[minVal] =
        CALCULATE ( MIN ( 'PBIpull'[Year Month Code] ) )

EVALUATE
{ CONCATENATE ( "Original: ", [Original] ) }

EVALUATE
{ CONCATENATE ( "Complex: ", [MeasureX] ) }

EVALUATE
{ CONCATENATE ( "CORRECT: ", [Correct] ) }

EVALUATE
{ CONCATENATE ( "VALOR COMPROBACIÓN: ", [rfmax] ) }

EVALUATE
{ CONCATENATE ( "MAX VAL: ", [maxVal] ) }
//Plan

EVALUATE
{ CONCATENATE ( "MIN VAL: ", [minVal] ) }
//202101

EVALUATE
{ CONCATENATE ( "2 RForecast-2022-07: ", [calrefor] ) }

EVALUATE
{ CONCATENATE ( "3 RForecast-2022-06: ", [rfmix] ) }

EVALUATE
{ CONCATENATE ( "4 Actuals - Sum: ", [calreless] ) }

EVALUATE
{ CONCATENATE ( "5 Sum: ", [sumresult] ) }
//
//DEFINE
//    MEASURE PBIpull[TotalPlus] =
//        CALCULATE (
//            SUM ( PBIpull[Count] ),
//            FILTER (
//                PBIpull,
//                AND ( PBIpull[Type] = "08&04 Reforecast", PBIpull[Year Month Code] < 202206 )
//            ),
//            FILTER ( PBIpull,  PBIpull[Count] > 0  )
//        )
//
//EVALUATE
//{ [TotalPlus] }
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
//EVALUATE
//CALCULATETABLE (
//    PBIpull,
//    FILTER (
//        PBIpull,
//        AND ( PBIpull[Type] = "Actuals", PBIpull[Year Month Code] >= 202206 )
//    ),
//    FILTER ( PBIpull, AND ( PBIpull[Count] > 0, PBIpull[Sub-Area] = "A1" ) )
//)
//EVALUATE
//CALCULATETABLE (
//    PBIpull,
//    FILTER (
//        PBIpull,
//        AND ( PBIpull[Type] = "08&04 Reforecast", PBIpull[Year Month Code] < 202206 )
//    ),
//    FILTER ( PBIpull, AND ( PBIpull[Count] > 0, PBIpull[Sub-Area] = "A1" ) )
//)
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
//DEFINE
//    MEASURE PBIpull[TotalPlus] =
//        CALCULATE (
//            SUM ( PBIpull[Count] ),
//            FILTER (
//                PBIpull,
//                AND ( PBIpull[Type] = "Actuals", PBIpull[Year Month Code] > 202206 )
//            ),
//            FILTER ( PBIpull,  PBIpull[Count] > 0  )
//        )
//
//EVALUATE
//{ [TotalPlus] }
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
//EVALUATE
//CALCULATETABLE (
//    SUMMARIZE (
//        PBIpull,
//        PBIpull[Type],
//        PBIpull[Year Month Code],
//        PBIpull[Year],
//        PBIpull[Sub-Area],
//        "Totals", SUM ( PBIpull[Count] )
//    ),
//    FILTER (
//        PBIpull,
//        AND ( PBIpull[Type] = "Actuals", PBIpull[Year Month Code] >= 202206 )
//    ),
//    FILTER ( PBIpull, AND ( PBIpull[Count] > 0, PBIpull[Sub-Area] = "A1" ) )
//)
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
//EVALUATE
//CALCULATETABLE (
//    SUMMARIZE (
//        PBIpull,
//        PBIpull[Type],
//        PBIpull[Year Month Code],
//        PBIpull[Year],
//        PBIpull[Sub-Area],
//        "Totals", SUM ( PBIpull[Count] )
//    ),
//    FILTER (
//        PBIpull,
//        AND ( PBIpull[Type] = "08&04 Reforecast", PBIpull[Year Month Code] < 202206 )
//    ),
//    FILTER ( PBIpull, AND ( PBIpull[Count] > 0, PBIpull[Sub-Area] = "A1" ) )
//)

-- :::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
-- Tabla: De un crimen dado muestra la suma total por año
-- Suma Valores por columna, filtra por crimen y muestra en tabla de año y variable encontrada
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
//DEFINE
//    MEASURE TempCasesComparison[Crimes Found] =
//        CALCULATE (
//            SUM ( TempCasesComparison[ENE] ) + SUM ( TempCasesComparison[FEB] )
//                + SUM ( TempCasesComparison[MAR] )
//                + SUM ( TempCasesComparison[ABR] )
//                + SUM ( TempCasesComparison[MAY] )
//                + SUM ( TempCasesComparison[JUN] )
//                + SUM ( TempCasesComparison[JUL] )
//                + SUM ( TempCasesComparison[AGO] )
//                + SUM ( TempCasesComparison[SEP] )
//                + SUM ( TempCasesComparison[OCT] )
//                + SUM ( TempCasesComparison[NOV] )
//                + SUM ( TempCasesComparison[DIC] ),
//            FILTER ( TempCasesComparison, TempCasesComparison[Crimen] = @Crimen )
//        )
//EVALUATE
//ADDCOLUMNS (
//    VALUES ( 'TempCasesComparison'[ANO] ),
//    "Crimenes Totales", [Crimes Found]
//)
//
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
-- Tabla: Total de Eventos por Año
-- Suma Valores por columna, filtra por crimen y muestra en tabla de año y variable encontrada
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
//DEFINE
//MEASURE
//TempCasesComparison[Result] =
//(
//    SUM ( TempCasesComparison[ENE] ) + SUM ( TempCasesComparison[FEB] )
//        + SUM ( TempCasesComparison[MAR] )
//        + SUM ( TempCasesComparison[ABR] )
//        + SUM ( TempCasesComparison[MAY] )
//        + SUM ( TempCasesComparison[JUN] )
//        + SUM ( TempCasesComparison[JUL] )
//        + SUM ( TempCasesComparison[AGO] )
//        + SUM ( TempCasesComparison[SEP] )
//        + SUM ( TempCasesComparison[OCT] )
//        + SUM ( TempCasesComparison[NOV] )
//        + SUM ( TempCasesComparison[DIC] )
//)
//
//EVALUATE
//ADDCOLUMNS ( VALUES ( 'TempCasesComparison'[ANO] ), "My Var:", [Result] )

-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
-- Tabla: Todos los crimenes presentados en el 2022
-- Calcula una tabla con los valores de crimenes y una condición
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
//EVALUATE
//CALCULATETABLE (
//    VALUES ( 'TempCasesComparison'[Crimen] ),
//    'TempCasesComparison'[ANO] = "2022"
//)

-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
-- Simple Measure Manipulation
-- Create measure, sumarize events and filter by two parameters
-- ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: --
//DEFINE
//    MEASURE TempCasesComparison[MeasureOne] =
//        CALCULATE (
//            (
//                SUM ( TempCasesComparison[ENE] ) + SUM ( TempCasesComparison[FEB] )
//                    + SUM ( TempCasesComparison[MAR] )
//                    + SUM ( TempCasesComparison[ABR] )
//                    + SUM ( TempCasesComparison[MAY] )
//                    + SUM ( TempCasesComparison[JUN] )
//                    + SUM ( TempCasesComparison[JUL] )
//                    + SUM ( TempCasesComparison[AGO] )
//                    + SUM ( TempCasesComparison[SEP] )
//                    + SUM ( TempCasesComparison[OCT] )
//                    + SUM ( TempCasesComparison[NOV] )
//                    + SUM ( TempCasesComparison[DIC] )
//            ),
//            FILTERS ( TempCasesComparison[Crimen] ),
//            TempCasesComparison[Crimen] IN { "Extorsión", "Secuestro" }
//        )
//
//EVALUATE
//{ [MeasureOne] }